site_name: Git Tutorial for non-programmers
docs_dir: src
site_dir: docs
nav:
    - Home: index.md
    - Git CLI: cli.md
    - Git GUI: gui.md
    - About: about.md
theme:
    name: material
    logo: assets/KCI-logo.png
    favicon: assets/KCI.ico
